In [16]:
import numpy as np
import pandas as pd

In [2]:
# numpy array from python array
myarr = np.array([45, 86, 41, 46, 56], np.int8)
myarr

array([45, 86, 41, 46, 56], dtype=int8)

In [3]:
zeros_arr = np.zeros((2,5))
zeros_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
space_arr = np.linspace(1, 4, 3)
space_arr

array([1. , 2.5, 4. ])

In [6]:
emp = np.empty((3, 5))
emp

array([[4.67296746e-307, 1.69121096e-306, 6.23047842e-307,
        2.22522597e-306, 1.33511969e-306],
       [1.37962320e-306, 9.34604358e-307, 9.79101082e-307,
        1.78020576e-306, 1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        2.29178686e-312, 2.66023306e-312]])

In [7]:
ide = np.identity(6)
ide

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

**2D Array**

In [8]:
x = [[1,2,3], [4,5,6], [7,1,0]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [9]:
arr.size

9

In [10]:
arr.shape

(3, 3)

In [11]:
arr.nbytes

72

In [12]:
arr.argmax()

np.int64(6)

In [13]:
arr.argmin()

np.int64(8)

In [17]:
my_array = np.linspace(0, 10, 50) + np.random.rand(50) * 2
my_array

array([ 0.83886903,  0.20538382,  1.60915218,  1.3452726 ,  0.88435199,
        2.62616438,  2.11621141,  2.60250416,  1.94339567,  3.28195834,
        3.65934055,  3.55977635,  3.06190893,  4.29273697,  3.67538826,
        3.3190687 ,  5.01017139,  3.58841521,  4.72122723,  4.34146025,
        4.94229557,  4.48308703,  5.92197258,  5.60716152,  6.64579444,
        6.27547702,  6.95271752,  7.42174882,  7.38115031,  7.00423659,
        7.59901995,  7.43086221,  8.06327362,  7.25875116,  8.26850462,
        8.72491713,  9.33563969,  8.31814839,  7.88717293,  8.15681741,
        9.55748567,  8.6591064 , 10.45593489,  9.25788916, 10.65888728,
       10.55818272, 11.03524491,  9.91442822, 11.51146368, 11.69054316])

In [18]:
array = np.linspace(0, 10, 50)
array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])